[tool.poetry]
name = "aws-arn-delete"
version = "0.1.1"
description = "Delete AWS resources based off its ARN"

license = "MIT"

authors = [
    "Christopher Farrenden <cfarrend@gmail.com>"
]

readme = 'README.md'

repository = "https://github.com/cfarrend/aws-arn-delete"
homepage = "https://github.com/cfarrend/aws-arn-delete"

keywords = ['aws', 'batect', 'pip', 'poetry', 'python3']

[tool.poetry.dependencies]
python = "^3.7.4"  # Compatible python versions must be declared here
toml = "^0.9"
# Dependencies with extras
# requests = { version = "^2.13", extras = [ "security" ] }
# Python specific dependencies with prereleases allowed
# pathlib2 = { version = "^2.2", python = "~2.7", allows-prereleases = true }

# Optional dependencies (extras)
# pendulum = { version = "^1.4", optional = true }

[tool.poetry.dev-dependencies]
black = "19.3b0"
pytest = "5.0.1"

# [tool.poetry.scripts]
# my-script = 'aws-arn-delete:main'
